# pocket-radio-deployment.yaml

# This section defines the Deployment for your application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocket-radio-deployment
  namespace: pocket-radio-app
  labels:
    app: pocket-radio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pocket-radio
  template:
    metadata:
      labels:
        app: pocket-radio
    spec:
      containers:
      - name: pocket-radio-container
        image: erezamsalem/pocket-radio-app:latest
        ports:
        - containerPort: 3001
        
        # --- THIS IS THE MISSING SECTION ---
        # It injects the API_KEY from your secret
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: pocket-radio-secret 
              key: API_KEY             

---

# This section defines the Service to expose your application.
apiVersion: v1
kind: Service
metadata:
  name: pocket-radio-service
  namespace: pocket-radio-app
spec:
  type: NodePort
  selector:
    app: pocket-radio
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001